#line 2 "input.yy.c"

#line 4 "input.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[476] =
    {   0,
        6,    6,   61,   60,    6,   60,    5,   60,   38,   60,
       60,    2,   60,   60,   60,   31,   60,   32,   60,   29,
       60,   27,   60,   37,   60,   28,   60,   60,   30,   60,
       47,   60,   59,   60,   43,   60,   26,   60,   41,   60,
       51,   60,16409,   51,   60,16409,   51,   60,16409,   51,
       60,16409,   35,   60,   36,   60,   51,   60,16409,   51,
       60,16409,   51,   60,16409,   51,   60,16409,   51,   60,
    16409,   51,   60,16409,   51,   60,16409,   51,   60,16409,
       33,   60,   60,   34,   60,    6,   60,    1,    2,   60,
       24,   51,   60,16409,   24,   51,   60,16409,   24,   51,

       60,16409,   24,   51,   60,16409,   24,   51,   60,16409,
       24,   51,   60,16409,   24,   51,   60,16409,   24,   51,
       60,16409,   24,   51,   60,16409,   24,   51,   60,16409,
       24,   51,   60,16409,   24,   51,   60,16409,    6,   46,
       52,    2,   39,   53,   49,    3,   48,   47,   44,   45,
       42,   51,16409, 8217,   51,16409,   51,16409,   51,16409,
       11,   51,16409,   51,16409,   12,   51,16409,   51,16409,
       51,16409,   51,16409,   51,16409,   51,16409,   51,16409,
       51,16409,   51,16409,   13,   51,16409,   51,16409,   51,
    16409,   51,16409,   40,    6,   24,    1,    2,   24,   51,

    16409,   24,   51,16409,   24,   51,16409,   24,   51,16409,
       11,   24,   51,16409,   24,   51,16409,   12,   24,   51,
    16409,   24,   51,16409,   24,   51,16409,   24,   51,16409,
       24,   51,16409,   24,   51,16409,   24,   51,16409,   24,
       51,16409,   24,   51,16409,   13,   24,   51,16409,   24,
       51,16409,   24,   51,16409,   24,   51,16409,    4,    3,
       48,   49,   50,   51,16409,   51,16409,   17,   51,16409,
       18,   51,16409,   51,16409,   51,16409,   51,16409,   51,
    16409,   51,16409,   51,16409,   21,   51,16409,   19,   51,
    16409,   51,16409,   51,16409,   51,16409,   24,   24,   51,

    16409,   24,   51,16409,   17,   24,   51,16409,   18,   24,
       51,16409,   24,   51,16409,   24,   51,16409,   24,   51,
    16409,   24,   51,16409,   24,   51,16409,   24,   51,16409,
       21,   24,   51,16409,   19,   24,   51,16409,   24,   51,
    16409,   24,   51,16409,   24,   51,16409,   49,   48,   51,
    16409,   51,16409,    8,   51,16409,   51,16409,    9,   51,
    16409,   20,   51,16409,   51,16409,   51,16409,   51,16409,
       51,16409,   10,   51,16409,   24,   51,16409,   24,   51,
    16409,    8,   24,   51,16409,   24,   51,16409,    9,   24,
       51,16409,   20,   24,   51,16409,   24,   51,16409,   24,

       51,16409,   24,   51,16409,   24,   51,16409,   10,   24,
       51,16409,   48,   49,   14,   51,16409,   15,   51,16409,
        7,   51,16409,   51,16409,   16,   51,16409,   51,16409,
       14,   24,   51,16409,   15,   24,   51,16409,    7,   24,
       51,16409,   24,   51,16409,   16,   24,   51,16409,   24,
       51,16409,   22,   51,16409,16439,   23,   51,16409,   22,
       24,   51,16409,   23,   24,   51,16409,16438, 8247,16441,
     8246, 8249,16440,   58, 8248
    } ;

static const flex_int16_t yy_accept[234] =
    {   0,
        1,    2,    3,    4,    5,    7,    9,   11,   12,   14,
       15,   16,   18,   20,   22,   24,   26,   28,   29,   31,
       33,   35,   37,   39,   41,   44,   47,   50,   53,   55,
       57,   60,   63,   66,   69,   72,   75,   78,   81,   83,
       84,   86,   88,   91,   95,   99,  103,  107,  111,  115,
      119,  123,  127,  131,  135,  139,  140,  140,  141,  141,
      142,  142,  143,  144,  144,  145,  145,  146,  147,  148,
      149,  149,  150,  151,  152,  152,  154,  155,  157,  159,
      161,  164,  166,  169,  171,  173,  175,  177,  179,  181,
      183,  185,  188,  190,  192,  194,  195,  196,  197,  199,

      202,  205,  208,  211,  215,  218,  222,  225,  228,  231,
      234,  237,  240,  243,  246,  250,  253,  256,  259,  259,
      260,  260,  260,  261,  263,  263,  263,  264,  266,  268,
      271,  274,  276,  278,  280,  282,  284,  286,  289,  292,
      294,  296,  298,  299,  302,  305,  309,  313,  316,  319,
      322,  325,  328,  331,  335,  339,  342,  345,  348,  348,
      349,  349,  349,  350,  352,  354,  357,  359,  362,  365,
      367,  369,  369,  371,  373,  376,  379,  382,  386,  389,
      393,  397,  400,  403,  406,  409,  413,  413,  415,  418,
      421,  424,  424,  426,  429,  429,  429,  431,  435,  439,

      443,  446,  450,  453,  453,  456,  456,  457,  457,  460,
      464,  468,  468,  469,  469,  469,  470,  470,  471,  471,
      471,  472,  472,  472,  473,  473,  473,  474,  474,  475,
      475,  476,  476
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   24,   24,   25,   26,   27,
       24,   24,   24,   24,   24,   28,   24,   29,   30,   24,
       24,   31,   32,   33,   34,   24,   24,   24,   24,   24,
       35,   36,   37,    1,   24,    1,   38,   39,   24,   40,

       41,   42,   43,   24,   44,   24,   24,   45,   24,   46,
       47,   24,   24,   48,   49,   50,   51,   24,   24,   24,
       24,   24,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[55] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    5,    1,    1,
        6,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    1,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[253] =
    {   0,
        0,   54,  589,  699,  107,  699,  104,  106,    0,  580,
      104,  699,  699,  699,  699,  699,  699,  536,  526,   98,
      699,  484,  458,  453,  113,  120,  124,  115,  699,  699,
      126,  127,  116,  129,  147,  131,  155,  158,  699,  414,
      699,  117,    0,  159,  160,  165,  169,  163,  167,  180,
      175,  183,  195,  201,  206,  128,  196,  699,  203,  699,
      450,    0,  699,  155,  699,  442,  194,    0,  205,  222,
      237,  699,  699,  699,  222,  235,  699,  239,  240,  247,
      251,  255,  256,  257,  262,  263,  268,  267,  271,  269,
      278,  273,  279,  277,  280,  699,  224,    0,    0,  284,

      285,  300,  301,  302,  305,  306,  308,  309,  322,  330,
      331,  333,  334,  332,  335,  337,  339,  342,  260,  699,
      421,  349,    0,  354,  353,  401,  390,  344,  336,  348,
      368,  379,  381,  386,  388,  389,  390,  394,  395,  396,
      399,  397,    0,  402,  401,  404,  410,  411,  419,  427,
      428,  433,  434,  440,  442,  444,  449,  445,  368,  343,
      444,  331,  330,  450,  454,  456,  467,  476,  478,  479,
      480,    0,  482,  483,  485,  488,  489,  490,  492,  494,
      505,  510,  515,  514,  516,  517,  322,  291,  518,  520,
      521,    0,  525,  526,  273,    0,  530,  538,  542,  543,

      546,  547,  548,  271,  550,  222,  551,  211,  555,  558,
      563,  193,  556,    0,  559,  699,  177,  572,    0,  579,
      699,  173,  580,  699,  165,  156,  583,  134,  699,  584,
      699,  699,  605,  613,  621,  628,  635,  643,  650,  658,
      666,  670,  147,  136,  674,  127,  678,  682,  119,  112,
      686,  690
    } ;

static const flex_int16_t yy_def[253] =
    {   0,
      232,  232,  232,  232,  232,  232,  232,  233,  234,  232,
      235,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  236,  236,  236,  236,  232,  232,
      236,  236,  236,  236,  236,  236,  236,  236,  232,  232,
      232,  237,  238,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  232,  240,  232,  233,  232,
      233,  234,  232,  235,  232,  235,  232,  241,  232,  232,
      232,  232,  232,  232,  232,  236,  232,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  232,  237,  242,  238,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  240,  232,
      240,  232,  241,  232,  232,  232,  232,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  242,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  232,  232,
      232,  232,  232,  236,  236,  236,  236,  236,  236,  236,
      236,  243,  236,  236,  236,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  232,  232,  236,  236,
      236,  244,  236,  236,  245,  246,  236,  239,  239,  239,

      239,  239,  239,  247,  236,  245,  232,  248,  236,  239,
      239,  247,  232,  249,  232,  232,  248,  232,  250,  232,
      232,  251,  232,  232,  252,  251,  232,  252,  232,  232,
      232,    0,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232
    } ;

static const flex_int16_t yy_nxt[754] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   25,   25,   25,   26,   25,   25,   27,
       25,   25,   28,   25,   29,    4,   30,   25,   31,   32,
       25,   33,   25,   34,   25,   25,   35,   36,   37,   38,
       25,   39,   40,   41,    4,   42,    6,    5,    7,    8,
       43,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   44,   44,   44,   44,
       45,   44,   44,   46,   44,   44,   47,   44,   29,    4,
       30,   44,   48,   49,   44,   50,   44,   51,   44,   44,

       52,   53,   54,   55,   44,   39,   40,   41,   56,   57,
       56,   60,   65,   69,   75,   70,   75,   75,   97,  225,
       56,   75,   71,   71,   58,   75,  222,   75,   75,   56,
       75,   56,   75,   77,  208,   77,   77,   71,   71,   66,
       77,   61,   78,  204,   77,   84,   77,   77,   75,   77,
       80,   77,   81,   89,  195,  229,   75,   79,   85,   75,
       75,   75,   86,   65,   75,   82,   75,   77,   75,   83,
       75,   93,   87,   88,   90,   77,   75,  227,   77,   77,
       77,   75,  101,   77,   75,   77,  229,   77,   91,   77,
       66,  103,   92,  104,  227,   77,   75,  102,  218,  107,

       77,  120,   75,   77,   94,   95,  105,   75,   60,  110,
      106,   67,  108,  111,  213,   77,  109,  112,  122,  122,
      113,   77,  124,   75,  114,   97,   77,   56,  115,  125,
      125,  121,  218,  122,  122,  116,   75,   69,   61,   70,
       75,   75,   77,  207,  125,  125,   71,   71,   75,  126,
      117,  126,   75,  118,  127,   77,   75,   75,   75,   77,
       77,   71,   71,   75,   75,  120,  128,   77,   75,   75,
       75,   77,   75,  130,   75,   77,   77,   77,   75,   75,
       75,   75,   77,   77,  129,   75,   75,   77,   77,   77,
      132,   77,  213,   77,  207,  121,  131,   77,   77,   77,

       77,   75,   75,   75,   77,   77,   75,   75,  188,   75,
       75,  133,  144,  134,  135,  137,  140,  136,  138,  139,
       77,   77,   77,   75,  141,   77,   77,  146,   77,   77,
      142,   75,   75,   75,   75,   75,   75,   75,   75,  188,
       75,  148,   77,   75,  145,   75,  147,  163,  163,   75,
       77,   77,   77,   77,   77,   77,   77,   77,  149,   77,
      160,  159,   77,  159,   77,  162,  160,  162,   77,   75,
      163,  124,  150,  155,  156,  164,  151,  153,  161,  161,
       75,  152,   75,  154,  165,  160,  157,   75,   77,   75,
       75,   75,  158,  161,  161,   75,   75,   75,   75,   77,

       75,   77,   75,   75,  166,   75,   77,  127,   77,   77,
       77,   75,   75,  172,   77,   77,   77,   77,  127,   77,
       75,   77,   77,  119,   77,  167,  168,  170,   75,   75,
       77,   77,  169,  176,   75,   75,  178,  175,  171,   77,
      173,   75,  174,   75,   64,   75,   75,   77,   77,  177,
       75,   75,   59,   77,   77,   75,  187,   75,  187,  172,
       77,  188,   77,  179,   77,   77,   96,  180,   75,   77,
       77,  182,  181,   74,   77,  189,   77,   75,   73,   75,
       75,   75,  183,   75,   75,  186,   75,   77,  184,   75,
       75,   75,  185,   75,  190,   75,   77,  192,   77,   77,

       77,  196,   77,   77,   72,   77,   75,  191,   77,   77,
       77,   75,   77,  198,   77,   75,   75,   75,   75,   75,
      194,   75,   75,  193,  192,   77,   75,   75,  197,  199,
       77,   75,  200,  196,   77,   77,   77,   77,   77,   75,
       77,   77,   68,   75,   75,   77,   77,   75,   75,   75,
       77,   75,  215,   67,  201,  202,   75,  220,   77,   75,
      215,  203,   77,   77,   75,  205,   77,   77,   77,  214,
       77,  216,  209,  223,  219,   77,  221,  214,   77,  216,
      220,  223,  219,   77,  230,  230,  210,   63,  232,  232,
      211,  232,  224,  232,  232,  232,  232,  232,  232,  221,

      224,  232,  232,  231,  231,   59,   59,  232,   59,   59,
       59,   59,   59,   62,   62,  232,   62,   62,   62,   62,
       62,   64,   64,  232,   64,   64,   64,   64,   64,   76,
      232,  232,   76,   76,  232,   76,   98,  232,   98,  232,
      232,  232,   98,   99,   99,  232,   99,   99,   99,   99,
       99,  100,  232,  232,  100,  100,  232,  100,  119,  119,
      232,  119,  119,  119,  119,  119,  123,  123,  232,  123,
      123,  123,  123,  123,  143,  232,  232,  143,  206,  232,
      206,  206,  212,  232,  212,  212,  217,  232,  217,  217,
      226,  232,  226,  226,  228,  232,  228,  228,    3,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232
    } ;

static const flex_int16_t yy_chk[754] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    5,    7,
        5,    8,   11,   20,   25,   20,   28,   33,   42,  250,
       42,   26,   20,   20,    7,   27,  249,   31,   32,   56,
       34,   56,   36,   25,  246,   28,   33,   20,   20,   11,
       26,    8,   26,  244,   27,   28,   31,   32,   35,   34,
       27,   36,   27,   33,  243,  228,   37,   26,   28,   38,
       44,   45,   28,   64,   48,   27,   46,   35,   49,   27,
       47,   36,   31,   32,   34,   37,   51,  226,   38,   44,
       45,   50,   45,   48,   52,   46,  225,   49,   35,   47,
       64,   46,   35,   46,  222,   51,   53,   45,  217,   47,

       50,   57,   54,   52,   37,   38,   46,   55,   59,   48,
       46,   67,   47,   49,  212,   53,   47,   50,   67,   67,
       51,   54,   69,   75,   52,   97,   55,   97,   52,   69,
       69,   57,  208,   67,   67,   53,   76,   70,   59,   70,
       78,   79,   75,  206,   69,   69,   70,   70,   80,   71,
       54,   71,   81,   55,   71,   76,   82,   83,   84,   78,
       79,   70,   70,   85,   86,  119,   78,   80,   88,   87,
       90,   81,   89,   80,   92,   82,   83,   84,   94,   91,
       93,   95,   85,   86,   79,  100,  101,   88,   87,   90,
       84,   89,  204,   92,  195,  119,   82,   94,   91,   93,

       95,  102,  103,  104,  100,  101,  105,  106,  188,  107,
      108,   85,  101,   86,   87,   89,   93,   88,   90,   91,
      102,  103,  104,  109,   94,  105,  106,  103,  107,  108,
       95,  110,  111,  114,  112,  113,  115,  129,  116,  187,
      117,  107,  109,  118,  102,  128,  105,  163,  162,  130,
      110,  111,  114,  112,  113,  115,  129,  116,  108,  117,
      160,  122,  118,  122,  128,  125,  122,  125,  130,  131,
      125,  124,  109,  114,  116,  128,  110,  112,  124,  124,
      132,  111,  133,  113,  129,  159,  117,  134,  131,  135,
      136,  137,  118,  124,  124,  138,  139,  140,  142,  132,

      141,  133,  145,  144,  132,  146,  134,  127,  135,  136,
      137,  147,  148,  138,  138,  139,  140,  142,  126,  141,
      149,  145,  144,  121,  146,  133,  134,  136,  150,  151,
      147,  148,  135,  144,  152,  153,  148,  142,  137,  149,
      140,  154,  141,  155,   66,  156,  158,  150,  151,  145,
      157,  164,   61,  152,  153,  165,  161,  166,  161,  154,
      154,  161,  155,  149,  156,  158,   40,  150,  167,  157,
      164,  152,  151,   24,  165,  164,  166,  168,   23,  169,
      170,  171,  153,  173,  174,  158,  175,  167,  156,  176,
      177,  178,  157,  179,  165,  180,  168,  169,  169,  170,

      171,  173,  173,  174,   22,  175,  181,  167,  176,  177,
      178,  182,  179,  176,  180,  184,  183,  185,  186,  189,
      171,  190,  191,  170,  181,  181,  193,  194,  174,  177,
      182,  197,  179,  184,  184,  183,  185,  186,  189,  198,
      190,  191,   19,  199,  200,  193,  194,  201,  202,  203,
      197,  205,  207,   18,  182,  183,  209,  213,  198,  210,
      215,  185,  199,  200,  211,  193,  201,  202,  203,  205,
      205,  207,  197,  218,  209,  209,  213,  210,  210,  215,
      220,  223,  211,  211,  227,  230,  201,   10,    3,    0,
      203,    0,  218,    0,    0,    0,    0,    0,    0,  220,

      223,    0,    0,  227,  230,  233,  233,    0,  233,  233,
      233,  233,  233,  234,  234,    0,  234,  234,  234,  234,
      234,  235,  235,    0,  235,  235,  235,  235,  235,  236,
        0,    0,  236,  236,    0,  236,  237,    0,  237,    0,
        0,    0,  237,  238,  238,    0,  238,  238,  238,  238,
      238,  239,    0,    0,  239,  239,    0,  239,  240,  240,
        0,  240,  240,  240,  240,  240,  241,  241,    0,  241,
      241,  241,  241,  241,  242,    0,    0,  242,  245,    0,
      245,  245,  247,    0,  247,  247,  248,    0,  248,  248,
      251,    0,  251,  251,  252,    0,  252,  252,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "input.l"
#line 2 "input.l"
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <ctype.h>
#include "input.tab.h"
#include <string>


#define YY_DECL int yylex( void * dummy )

#define KEY_DEFINE      1
#define BOOL_DEFINE     3
#define INT_DEFINE      4
#define REAL_DEFINE     5
#define STRING_DEFINE   6
#define DEFINE_RHS      7

// we have to use this to find parameter type
static std::string keyword;
static int state;
static int error_report(const char *s);
//#define VERBOSE



#line 787 "input.yy.c"
#line 788 "input.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "input.l"



#line 1018 "input.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 699 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 47 "input.l"
{/* comment line */      return COMMENT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "input.l"
{/* inline comment */    return COMMENT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "input.l"
{/* c++ style comment */ return COMMENT;}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 53 "input.l"
{ yytext[yyleng-1]='\0'; strncpy(yylval.sval, &yytext[2], 1023); return LINEINFO;  }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 55 "input.l"
{/* new command */ state = 0;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "input.l"
{/* use to drop blankspace/tab/cr */}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "input.l"
{  strncpy(yylval.sval, yytext,1023); return TITLE;}
	YY_BREAK
case 8:
#line 64 "input.l"
case 9:
#line 65 "input.l"
case 10:
#line 66 "input.l"
case 11:
#line 67 "input.l"
case 12:
#line 68 "input.l"
case 13:
YY_RULE_SETUP
#line 68 "input.l"
{ yylval.bval = true;    return BOOL_VALUE;}
	YY_BREAK
case 14:
#line 73 "input.l"
case 15:
#line 74 "input.l"
case 16:
#line 75 "input.l"
case 17:
#line 76 "input.l"
case 18:
#line 77 "input.l"
case 19:
YY_RULE_SETUP
#line 77 "input.l"
{ yylval.bval = false;  return BOOL_VALUE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "input.l"
{ state = BOOL_DEFINE;   return BOOL_TYPE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "input.l"
{ state = INT_DEFINE;    return INT_TYPE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "input.l"
{ state = REAL_DEFINE;   return REAL_TYPE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "input.l"
{ state = STRING_DEFINE; return STRING_TYPE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "input.l"
{

        // at first, we should drop blank chars
        char * cp = yylval.sval;
        for(unsigned int c=0;c<strlen(yytext)+1;c++)
        {
          if (yytext[c] == '\t' || isspace(yytext[c]))
            continue;
          *cp++ = yytext[c];
        }

        Parser::InputParser * p = (Parser::InputParser *) dummy;
        //does this string match any ID?
        if( state==0 )
        {
          std::string name = yylval.sval;
          if(p->bool_var.count(name))        { return BOOL_ID;       }
          if(p->int_var.count(name))         { return INT_ID;        }
          if(p->real_var.count(name))        { return REAL_ID;       }
          if(p->string_var.count(name))      { return STRING_ID;     }
        }

        //At last, this should be a keyword
        state = KEY_DEFINE;

        //change it to upper case
        for(unsigned int c=0;c<strlen(yylval.sval);c++)
        {
          if(islower(yylval.sval[c]))
            yylval.sval[c]=toupper(yylval.sval[c]);
        }

        // can we find this token in card pattern?
        keyword = yylval.sval;
        if(p->_pattern.ckeck_card(keyword))
        {
          error_report(yytext);
        }
        // return exact card name
        strcpy(yylval.sval, keyword.c_str());
#ifdef VERBOSE
        printf("KEYWORD %s\n",yylval.sval);
#endif
        return KEYWORD;

        //we should never reach here
        error_report(yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 139 "input.l"
{

        // A string followed by '='

        //for the state of BOOL_DEFINE, this token should be BOOL_ID
        if (state == BOOL_DEFINE)
        {
          strncpy(yylval.sval, yytext,1023);
#ifdef VERBOSE
        printf("BOOL_ID %s\n",yytext);
#endif
          return BOOL_ID;
        }
        if (state == INT_DEFINE)
        {
          strncpy(yylval.sval, yytext,1023);
#ifdef VERBOSE
        printf("INT_ID %s\n",yytext);
#endif
          return INT_ID;
        }
        if (state == REAL_DEFINE)
        {
          strncpy(yylval.sval, yytext,1023);
#ifdef VERBOSE
        printf("REAL_ID %s\n",yytext);
#endif
          return REAL_ID;
        }
        if (state == STRING_DEFINE)
        {
          strncpy(yylval.sval, yytext,1023);
#ifdef VERBOSE
        printf("STRING_ID %s\n",yytext);
#endif
          return STRING_ID;
        }

        //for the state of KEY DEFINE, it should be parameter
        Parser::InputParser * p = (Parser::InputParser *) dummy;
        if (state == KEY_DEFINE)
        {
          strncpy(yylval.sval, yytext,1023);
          for(unsigned int c=0;c<strlen(yylval.sval);c++)
          {
            if(isupper(yylval.sval[c]))
              yylval.sval[c]=tolower(yylval.sval[c]);
          }

          std::string pname = yylval.sval;
          Parser::ElemType type = p->_pattern.check_parameter_type(keyword, pname);
          strcpy(yylval.sval, pname.c_str());
#ifdef VERBOSE
          printf("PARAMETER_ID %s type %d\n",yylval.sval, type);
#endif
          switch ( type )
          {
            case        Parser::BOOL      :  return BOOL_PARAMETER;
            case        Parser::INTEGER   :  return INT_PARAMETER;
            case        Parser::REAL      :  ;return REAL_PARAMETER;
            case        Parser::STRING    :  ;return STRING_PARAMETER;
            case        Parser::ENUM      :  ;return STRING_PARAMETER;
            default:    break;
          }
          // if user mistakenly input an wrong parameter, however it matches ID
          // YACC will pick this mistake later
        }

        // for a general assign statement, it maybe an ID
        // find if this token belongs to any existing ID
        strncpy(yylval.sval, yytext,1023);
        std::string name = yylval.sval;

        if(p->bool_var.count(name))
        {
#ifdef VERBOSE
              printf("BOOL_ID %s\n",yytext);
#endif
          return BOOL_ID;
        }

        if(p->int_var.count(name))
        {
#ifdef VERBOSE
            printf("INT_ID %s\n",yytext);
#endif
          return INT_ID;
        }
        if(p->real_var.count(name))
        {
#ifdef VERBOSE
            printf("REAL_ID %s\n",yytext);
#endif
          return REAL_ID;
        }
        if(p->string_var.count(name))
        {
#ifdef VERBOSE
            printf("STRING_ID %s\n",yytext);
#endif
          return STRING_ID;
        }

        //we should never reach here
        error_report(yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 247 "input.l"
{ return '=';  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 249 "input.l"
{ return PLUS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 251 "input.l"
{ return MINUS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 253 "input.l"
{ return ASTERISK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 255 "input.l"
{ return DIVIDE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 257 "input.l"
{ return '('; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 259 "input.l"
{ return ')'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 261 "input.l"
{ return '{'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 263 "input.l"
{ return '}'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 265 "input.l"
{ return '['; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 267 "input.l"
{ return ']'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 269 "input.l"
{ return ','; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 271 "input.l"
{ return NOT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 273 "input.l"
{ return AND;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 275 "input.l"
{ return OR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "input.l"
{ return GT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 279 "input.l"
{ return GE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 281 "input.l"
{ return LT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 283 "input.l"
{ return LE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 285 "input.l"
{ return EQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 287 "input.l"
{ return NE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 289 "input.l"
{
    // NOTE: input deck some times have big number, i.e. 2397610736220310
    // which will be parsed as int. However, int will be overflow for such a big value
    int    i;
    double d;
    sscanf(yytext, "%d", &i);
    sscanf(yytext, "%lf", &d);
    if( i == floor(d+0.5) )
    {
      yylval.ival = i;
      return INT_VALUE;
    }

    yylval.dval = d;
    return REAL_VALUE;
}
	YY_BREAK
case 48:
#line 308 "input.l"
case 49:
#line 309 "input.l"
case 50:
YY_RULE_SETUP
#line 309 "input.l"
{sscanf(yytext, "%lf", &yylval.dval);return REAL_VALUE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 313 "input.l"
{

        // find if this token belongs to any exist ID
        strncpy(yylval.sval, yytext,1023);
        std::string name = yylval.sval;

        Parser::InputParser * p = (Parser::InputParser *) dummy;
        if(p->bool_var.count(name))
        {
          return BOOL_ID;
        }

        if(p->int_var.count(name))
        {
          return INT_ID;
        }
        if(p->real_var.count(name))
        {
          return REAL_ID;
        }
        if(p->string_var.count(name))
        {
          return STRING_ID;
        }
#ifdef VERBOSE
        printf("STRING_VALUE %s\n",yylval.sval);
#endif
        // at larst, return as STRING_VALUE;
        return STRING_VALUE;

        //we should never reach here
        error_report(yytext);
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 348 "input.l"
{
        // c style string
        // the only poissable is STRING_VALUE
        yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[1],1023);
#ifdef VERBOSE
        printf("STRING_VALUE %s\n",yylval.sval);
#endif
        return STRING_VALUE;
}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 360 "input.l"
{
        // fortran style string
        // the only poissable is STRING_VALUE
    yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[1],1023);
#ifdef VERBOSE
        printf("STRING_VALUE %s\n",yylval.sval);
#endif
        return STRING_VALUE;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 373 "input.l"
{
       // user defined parameter name
       // the parameter type is bool

        yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[strlen("bool<")],1023);
        return UD_BOOL_PARAMETER;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 383 "input.l"
{
       // user defined parameter name
       // the parameter type is int

        yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[strlen("int<")],1023);
        return UD_INT_PARAMETER;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 393 "input.l"
{
       // user defined parameter name
       // the parameter type is real

        yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[strlen("double<")],1023);
        return UD_REAL_PARAMETER;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 403 "input.l"
{
       // user defined parameter name
       // the parameter type is real

        yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[strlen("real<")],1023);
        return UD_REAL_PARAMETER;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 413 "input.l"
{
       // user defined parameter name
       // the parameter type is string

        yytext[yyleng-1]='\0';
        strncpy(yylval.sval, &yytext[strlen("string<")],1023);
        return UD_STRING_PARAMETER;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 423 "input.l"
{state = 0; return ';';}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 426 "input.l"
{return 0;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 428 "input.l"
ECHO;
	YY_BREAK
#line 1623 "input.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 232);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 428 "input.l"


static int error_report(const char * s)
{
  std::cerr  << "ERROR: token "<<s<<" can't be matched."<<std::endl;
  //std::cerr  << "ERROR at " << __FILE__ << ", line " << __LINE__ << std::endl;
  return 1;
}


